### ISSUE TITLE
implement 2 buttons - one for changing font style, one for changing font color

### ISSUE THREAD

**Issue by isaacstaugaard** [UCSB-CS56-Projects/cs56-misc-translate-to-secret-languages#11]
allow the user to easily switch between font styles and font colors 
estimated ~200pts

**Comment by PazZaitGivon** [comment]
ehh cant find this functionality. not in ant PigLatin.

**Comment by ashedden** [comment]
This issue has not been implemented on the master branch. I'm guessing that this issue can be solved with adding a font button that opens another pop-up full open style and color options? Issue is still open!
