### ISSUE TITLE
Update the GUI

### ISSUE THREAD

**Issue by isaacstaugaard** [UCSB-CS56-Projects/cs56-misc-translate-to-secret-languages#12]
Change the GUI to have a better layout for the buttons, including changing the frames for the "Help", "Font Color", and "Font Style" buttons. I'd suggest changing the options for "English to Pig Latin", "Pig Latin to English", etc. to resemble a drop down menu (like the ant Gibberish GUI). All the buttons should be the same size and better aligned.
estimated ~175pts

**Comment by PazZaitGivon** [comment]
Looks good

**Comment by ashedden** [comment]
I do not see a help button implemented, and the buttons are not implemented either ( #11 ). I'd say this issue should focus mostly on adding the help buttons and and organized the buttons on the pop-up. Issue is still open!

~estimated 150
