### ISSUE TITLE
Implement new fonts/colors and allow for changing fonts while maintaining bold/italics/plain

### ISSUE THREAD

**Issue by isaacstaugaard** [UCSB-CS56-Projects/cs56-misc-translate-to-secret-languages#13]
There are only a couple fonts and colors added right now. Add some more.
Also, let the user change the font while keeping the bold/italic/plain style. Allow stacking i.e. letting a font have bold/italic at the same time. 
Estimated ~75pts

**Comment by PazZaitGivon** [comment]
Looks good

**Comment by ashedden** [comment]
I have not seen this implemented in the GUIs. This issue goes alongside issue #11. Issue is still open!

**Comment by ashedden** [comment]
Approved!
