### ISSUE TITLE
Add a New Language. 250 pts

### ISSUE THREAD

**Issue by ashedden** [ucsb-cs56-projects/cs56-misc-translate-to-secret-languages#21]
You can never have too many! Obish sounds pretty fun; he's a website explaining how the language works.

http://www.instructables.com/id/How-to-speak-Obish/?ALLSTEPS

~estimated 200

**Comment by ashedden** [comment]
W16 ok!

**Comment by jmangel** [comment]
F16 OK (200 pts)

**Comment by john-lau** [comment]
W18 OK. 250 pts

**Comment by john-lau** [comment]
closed with pull request #57
