### ISSUE TITLE
make PigToEng automatically select if there's only one option

### ISSUE THREAD

**Issue by jmangel** [UCSB-CS56-Projects/cs56-misc-translate-to-secret-languages#30]
As it is, PigToEnglish has to wait for user to select each word from its dropdown before displaying it in the output field. Some actionListener or function should check each word to see if there is only one option, in which case it should programmatically select that option. (keep in mind that to keep an empty option at index 0, JComboBox.getItemCount() will return 1 more than the number of valid options)

~50 points

**Comment by ashedden** [comment]
Approved!
