### ISSUE TITLE
Fix all code indentation! 150 pts

### ISSUE THREAD

**Issue by FrostyNarwhal** [ucsb-cs56-projects/cs56-misc-translate-to-secret-languages#33]
The indentation in most all the files is super inconsistent and confusing, make it look hella fine!

~75-100 points

**Comment by ashedden** [comment]
W16 hella ok!

**Comment by jmangel** [comment]
F16 OK (100 pts)

**Comment by john-lau** [comment]
W18 OK. 150 pts

**Comment by john-lau** [comment]
closed with pull request #57
