### ISSUE TITLE
Update target descriptions in build.xml. 25 pts

### ISSUE THREAD

**Issue by jmangel** [ucsb-cs56-projects/cs56-misc-translate-to-secret-languages#36]
In build.xml, every target should have a `description` attribute describing the target. Add descriptions for those without it. The description for the 'test' target is also incomplete. Figure out what else it does and adjust the description accordingly

50 points

**Comment by jmangel** [comment]
The description for the 'test' target is also incomplete. Figure out what else it does and adjust the description accordingly

25 points

**Comment by jmangel** [comment]
F16 OK (25 pts)

**Comment by john-lau** [comment]
F18 OK. 25 pts

**Comment by john-lau** [comment]
closed with pull request #57
