### ISSUE TITLE
Update missing javadoc method descriptions. 50 pts

### ISSUE THREAD

**Issue by jmangel** [ucsb-cs56-projects/cs56-misc-translate-to-secret-languages#38]
Some methods, some examples listed below, do not have javadoc comments. Figure out what these methods do and add a description in the form of a javadoc comment 
- posFirstVowel() in EnglishToGibberish and EnglishToPigLatin (and combined_translator's copies of both of these files)
- testNullString() in EnglishToPigLatinTester (and combined_translator)
- most of the methods in combined_translator.WindowSetUp

~100 points

**Comment by jmangel** [comment]
F16 OK (50 pts)

**Comment by john-lau** [comment]
F18 OK. 50 pts

**Comment by john-lau** [comment]
closed with pull request #50
