### ISSUE TITLE
Clean up extra files. 25 pts

### ISSUE THREAD

**Issue by jmangel** [ucsb-cs56-projects/cs56-misc-translate-to-secret-languages#39]
EnglishToGibberish and its tester are included under pig_latin_translator. These are not relevant to that part of the project. Make sure that these are not necessary for the project (testing) and remove them if possible.

~50 points

**Comment by jmangel** [comment]
F16 OK (25 pts)

**Comment by john-lau** [comment]
F18 OK. 25 pts

**Comment by john-lau** [comment]
closed with pull request #57
