### ISSUE TITLE
Full refactor. 400 pts

### ISSUE THREAD

**Issue by izinman** [ucsb-cs56-projects/cs56-misc-translate-to-secret-languages#45]
Currently, tons of code is duplicated across the 3 folders in src. We need to combine this into one, unified folder which has all types of translators, and in the process combine and simplify the GUI creation process. This will involve figuring out what code is functional and what is duplicated, seeing how to add all 3 translator interfaces into one, and modifying the build file as needed to make it all compile and run.

**Comment by john-lau** [comment]
W18 OK.

**Comment by john-lau** [comment]
closed with pull request #50
