### ISSUE TITLE
Finish refactor: 150 pts

### ISSUE THREAD

**Issue by izinman** [ucsb-cs56-projects/cs56-misc-translate-to-secret-languages#51]
The first part of the refactor tackled code duplication and readability. This next stage will focus on improving object-orientation by moving translation logic from WindowSetUp.java (which should optimally be just a GUI class) to the actual translator classes.

**Comment by john-lau** [comment]
W18 OK. 250 pts

**Comment by john-lau** [comment]
closed with pull request #53
